package email

import (
	"fmt"
	"log/slog"
	"net/smtp"
	"strings"
)

type Config struct {
	SMTPHost  string
	SMTPPort  int
	SMTPUser  string
	SMTPPass  string
	FromEmail string
	FromName  string
}

type ReportEmail struct {
	To          string
	ShopName    string
	Date        string
	TotalSales  int64
	TotalCash   int64
	TotalMpesa  int64
	SaleCount   int
	Currency    string
	WorkerStats []WorkerStat
}

type WorkerStat struct {
	Name  string
	Sales int
	Total int64
}

func SendReport(cfg Config, report ReportEmail) error {
	if cfg.SMTPHost == "" || cfg.SMTPUser == "" {
		slog.Warn("email not configured — skipping report", "to", report.To)
		return nil
	}

	subject := fmt.Sprintf("Daily Sales Report — %s — %s", report.ShopName, report.Date)

	body := buildEmail(report)

	msg := fmt.Sprintf("From: %s <%s>\r\nTo: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n%s",
		cfg.FromName, cfg.FromEmail, report.To, subject, body)

	addr := fmt.Sprintf("%s:%d", cfg.SMTPHost, cfg.SMTPPort)
	auth := smtp.PlainAuth("", cfg.SMTPUser, cfg.SMTPPass, cfg.SMTPHost)

	err := smtp.SendMail(addr, auth, cfg.FromEmail, []string{report.To}, []byte(msg))
	if err != nil {
		return fmt.Errorf("send email: %w", err)
	}

	slog.Info("daily report sent", "to", report.To, "shop", report.ShopName, "date", report.Date)
	return nil
}

func buildEmail(r ReportEmail) string {
	workerRows := ""
	for _, ws := range r.WorkerStats {
		workerRows += fmt.Sprintf(`<tr>
			<td style="padding:10px;border-bottom:1px solid #e8e9eb">%s</td>
			<td style="padding:10px;border-bottom:1px solid #e8e9eb;text-align:center">%d</td>
			<td style="padding:10px;border-bottom:1px solid #e8e9eb;text-align:right;font-weight:600">%s %d</td>
		</tr>`, ws.Name, ws.Sales, r.Currency, ws.Total)
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f5f6f8;font-family:Inter,-apple-system,sans-serif">
<table width="100%%" cellpadding="0" cellspacing="0" style="background:#f5f6f8;padding:40px 0">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
<tr><td style="background:#1a1a2e;padding:24px;text-align:center">
<h1 style="color:#ffffff;margin:0;font-size:20px;font-weight:700">Mini-Database</h1>
<p style="color:#82b440;margin:4px 0 0;font-size:12px">Daily Sales Report</p>
</td></tr>
<tr><td style="padding:28px">
<h2 style="margin:0 0 4px;font-size:18px;color:#1a1a2e">%s</h2>
<p style="margin:0 0 24px;color:#6b7280;font-size:14px">%s</p>

<table width="100%%" cellpadding="0" cellspacing="0" style="margin-bottom:24px">
<tr>
<td style="padding:16px;background:#e8f5d8;border-radius:8px;text-align:center">
<div style="font-size:12px;color:#6b7280;margin-bottom:4px">Total Sales</div>
<div style="font-size:24px;font-weight:700;color:#1a1a2e">%s %d</div>
</td>
<td style="width:12px"></td>
<td style="padding:16px;background:#eff6ff;border-radius:8px;text-align:center">
<div style="font-size:12px;color:#6b7280;margin-bottom:4px">Transactions</div>
<div style="font-size:24px;font-weight:700;color:#1a1a2e">%d</div>
</td>
</tr>
</table>

<table width="100%%" cellpadding="0" cellspacing="0" style="margin-bottom:24px">
<tr>
<td style="padding:12px;background:#f5f6f8;border-radius:8px;text-align:center">
<div style="font-size:11px;color:#6b7280">Cash</div>
<div style="font-size:16px;font-weight:600;color:#1a1a2e">%s %d</div>
</td>
<td style="width:8px"></td>
<td style="padding:12px;background:#f5f6f8;border-radius:8px;text-align:center">
<div style="font-size:11px;color:#6b7280">M-Pesa</div>
<div style="font-size:16px;font-weight:600;color:#1a1a2e">%s %d</div>
</td>
</tr>
</table>

<h3 style="margin:0 0 12px;font-size:14px;color:#1a1a2e">Sales by Worker</h3>
<table width="100%%" cellpadding="0" cellspacing="0" style="border:1px solid #e8e9eb;border-radius:8px;overflow:hidden">
<tr style="background:#fafbfc">
<th style="padding:10px;text-align:left;font-size:11px;color:#9ca3af;text-transform:uppercase">Worker</th>
<th style="padding:10px;text-align:center;font-size:11px;color:#9ca3af;text-transform:uppercase">Sales</th>
<th style="padding:10px;text-align:right;font-size:11px;color:#9ca3af;text-transform:uppercase">Total</th>
</tr>
%s
</table>

<p style="margin:24px 0 0;color:#9ca3af;font-size:11px;text-align:center">Generated by Mini-Database POS</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>`,
		r.ShopName, r.Date,
		r.Currency, r.TotalSales,
		r.SaleCount,
		r.Currency, r.TotalCash,
		r.Currency, r.TotalMpesa,
		workerRows,
	)
}

func ValidateConfig(cfg Config) error {
	var missing []string
	if cfg.SMTPHost == "" {
		missing = append(missing, "SMTP_HOST")
	}
	if cfg.SMTPPort == 0 {
		missing = append(missing, "SMTP_PORT")
	}
	if cfg.SMTPUser == "" {
		missing = append(missing, "SMTP_USER")
	}
	if cfg.SMTPPass == "" {
		missing = append(missing, "SMTP_PASS")
	}
	if cfg.FromEmail == "" {
		missing = append(missing, "EMAIL_FROM")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing email config: %s", strings.Join(missing, ", "))
	}
	return nil
}
