package receipt

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

type Receipt struct {
	ShopName    string
	ShopAddress string
	ReceiptNo   string
	Date        time.Time
	Items       []ReceiptItem
	Subtotal    int64
	Tax         int64
	Total       int64
	Payment     string
	Worker      string
	Currency    string
}

type ReceiptItem struct {
	Name     string
	Quantity int64
	Price    int64
	Total    int64
}

func GeneratePDF(r Receipt) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	lineW := 170.0
	x := 20.0
	y := 20.0

	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(26, 26, 46)
	pdf.CellFormat(lineW, 10, r.ShopName, "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(107, 114, 128)
	if r.ShopAddress != "" {
		pdf.CellFormat(lineW, 6, r.ShopAddress, "", 1, "C", false, 0, "")
	}

	y += 20
	pdf.SetDrawColor(232, 233, 235)
	pdf.Line(x, y, x+lineW, y)
	y += 8

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(26, 26, 46)
	pdf.CellFormat(80, 6, fmt.Sprintf("Receipt: %s", r.ReceiptNo), "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 6, fmt.Sprintf("Date: %s", r.Date.Format("02 Jan 2006 15:04")), "", 1, "R", false, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(107, 114, 128)
	pdf.CellFormat(80, 5, fmt.Sprintf("Cashier: %s", r.Worker), "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 5, fmt.Sprintf("Payment: %s", r.Payment), "", 1, "R", false, 0, "")

	y += 10
	pdf.Line(x, y, x+lineW, y)
	y += 8

	// Table header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(26, 26, 46)
	pdf.SetFillColor(245, 246, 248)
	pdf.CellFormat(70, 7, "Item", "0", 0, "L", true, 0, "")
	pdf.CellFormat(20, 7, "Qty", "0", 0, "C", true, 0, "")
	pdf.CellFormat(35, 7, "Price", "0", 0, "R", true, 0, "")
	pdf.CellFormat(45, 7, "Total", "0", 1, "R", true, 0, "")

	// Items
	pdf.SetFont("Helvetica", "", 9)
	for _, item := range r.Items {
		pdf.CellFormat(70, 7, item.Name, "0", 0, "L", false, 0, "")
		pdf.CellFormat(20, 7, fmt.Sprintf("%d", item.Quantity), "0", 0, "C", false, 0, "")
		pdf.CellFormat(35, 7, fmt.Sprintf("%s %d", r.Currency, item.Price), "0", 0, "R", false, 0, "")
		pdf.CellFormat(45, 7, fmt.Sprintf("%s %d", r.Currency, item.Total), "0", 1, "R", false, 0, "")
	}

	y += 8
	pdf.Line(x, y, x+lineW, y)
	y += 8

	// Totals
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(107, 114, 128)
	pdf.CellFormat(95, 7, "Subtotal", "", 0, "L", false, 0, "")
	pdf.CellFormat(75, 7, fmt.Sprintf("%s %d", r.Currency, r.Subtotal), "", 1, "R", false, 0, "")

	if r.Tax > 0 {
		pdf.CellFormat(95, 7, "Tax", "", 0, "L", false, 0, "")
		pdf.CellFormat(75, 7, fmt.Sprintf("%s %d", r.Currency, r.Tax), "", 1, "R", false, 0, "")
	}

	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(26, 26, 46)
	pdf.CellFormat(95, 10, "Total", "", 0, "L", false, 0, "")
	pdf.CellFormat(75, 10, fmt.Sprintf("%s %d", r.Currency, r.Total), "", 1, "R", false, 0, "")

	y += 14
	pdf.Line(x, y, x+lineW, y)
	y += 10

	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(156, 163, 175)
	pdf.CellFormat(lineW, 5, "Thank you for your purchase!", "", 1, "C", false, 0, "")
	pdf.CellFormat(lineW, 5, fmt.Sprintf("Generated by Mini-Database POS | %s", time.Now().Format("2006-01-02 15:04:05")), "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("generate PDF: %w", err)
	}
	return buf.Bytes(), nil
}
